// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eshaxszgdgunvhcfulgd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVzaGF4c3pnZGd1bnZoY2Z1bGdkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2NTU2NDQsImV4cCI6MjA2NTIzMTY0NH0.OSyeuaqK1E9Lpqx9fHJGJ-c4mqISxJrr189m_Xac98g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);